<<<<<<< Updated upstream
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      USDA_API_KEY: ${USDA_API_KEY}
      BAIDU_TRANSLATE_APPID: ${BAIDU_TRANSLATE_APPID}
      BAIDU_TRANSLATE_APPKEY: ${BAIDU_TRANSLATE_APPKEY}
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./front_vue
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
=======
version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-flask-app:latest
    restart: always
    environment:
      - FLASK_APP=backend/app2.py
      - FLASK_ENV=production
      - DOCKER_ENV=true
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@db/flaskdb
      - USDA_API_KEY=${USDA_API_KEY}
      - BAIDU_TRANSLATE_APPID=${BAIDU_TRANSLATE_APPID}
      - BAIDU_TRANSLATE_APPKEY=${BAIDU_TRANSLATE_APPKEY}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=flaskdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - flask-app
>>>>>>> Stashed changes
    networks:
      - app-network

networks:
  app-network:
<<<<<<< Updated upstream
    driver: bridge

volumes:
  db_data:
=======

volumes:
  mysql-data:
>>>>>>> Stashed changes
